// 初始数据
const initialState = {
  count: 7,
  data: [],
  sangji: {
    nodes: [],
    links: [],
  },
  all: {
    nodes: [],
    links: [],
  },
  empty: {
    nodes: [],
    links: [],
  },
  add: [
    [{ name: "survive" }, { name: "sex-female" }, { name: "sex-male" }],
    [
      { name: "survive" },
      { name: "sex-female" },
      { name: "sex-male" },
      { name: "pclass-1" },
      { name: "pclass-2" },
      { name: "pclass-3" },
    ],
    [
      { name: "survive" },
      { name: "sex-female" },
      { name: "sex-male" },
      { name: "pclass-1" },
      { name: "pclass-2" },
      { name: "pclass-3" },
      { name: "fare<50" },
      { name: "50<fare<100" },
      { name: "fare>100" },
    ],
    [
      { name: "survive" },
      { name: "sex-female" },
      { name: "sex-male" },
      { name: "pclass-1" },
      { name: "pclass-2" },
      { name: "pclass-3" },
      { name: "fare<50" },
      { name: "50<fare<100" },
      { name: "fare>100" },
      { name: "embark-C" },
      { name: "embark-S" },
      { name: "embark-Q" },
    ],
    [
      { name: "survive" },
      { name: "sex-female" },
      { name: "sex-male" },
      { name: "pclass-1" },
      { name: "pclass-2" },
      { name: "pclass-3" },
      { name: "fare<50" },
      { name: "50<fare<100" },
      { name: "fare>100" },
      { name: "embark-C" },
      { name: "embark-S" },
      { name: "embark-Q" },
      { name: "age<15" },
      { name: "15<age<40" },
      { name: "40<age<65" },
      { name: "age>65" },
    ],
    [
      { name: "survive" },
      { name: "sex-female" },
      { name: "sex-male" },
      { name: "pclass-1" },
      { name: "pclass-2" },
      { name: "pclass-3" },
      { name: "fare<50" },
      { name: "50<fare<100" },
      { name: "fare>100" },
      { name: "embark-C" },
      { name: "embark-S" },
      { name: "embark-Q" },
      { name: "age<15" },
      { name: "15<age<40" },
      { name: "40<age<65" },
      { name: "age>65" },
      { name: "parch-0" },
      { name: "parch-1" },
      { name: "parch>1" },
    ],
    [
      { name: "survive" },
      { name: "sex-female" },
      { name: "sex-male" },
      { name: "pclass-1" },
      { name: "pclass-2" },
      { name: "pclass-3" },
      { name: "fare<50" },
      { name: "50<fare<100" },
      { name: "fare>100" },
      { name: "embark-C" },
      { name: "embark-S" },
      { name: "embark-Q" },
      { name: "age<15" },
      { name: "15<age<40" },
      { name: "40<age<65" },
      { name: "age>65" },
      { name: "parch-0" },
      { name: "parch-1" },
      { name: "parch>1" },
      { name: "sibsp-0" },
      { name: "sibsp-1" },
      { name: "sibsp>1" },
    ],
  ],
};

export default initialState;
